logging:
  file: C:\\temp\\intelliJ_logs\\spring-springintegration.log
  level:
    com: DEBUG
    root: INFO

spring:
  profiles:
    active: ${profile:local}
    include: $(ENV_NAME:local}
  application:
    name: spring-springintegration
  output:
    ansi:
      enabled: always

services:
  tracking:
    url: https://google.com
    timeout: 10000